//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSach
    {
        public int MaDanhGia { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> IDSach { get; set; }
        public Nullable<int> DiemDanhGia { get; set; }
        public string NhanXet { get; set; }
    }
}
