//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonTraSach
    {
        public int IDMuonTra { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> IDSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTraDuKien { get; set; }
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
        public Nullable<int> SoTienPhat { get; set; }
        public string TinhTrang { get; set; }
    }
}
