//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int IDNguoiDung { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public string Lop { get; set; }
        public string ChuyenNganh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string GioiThieu { get; set; }
        public string LichSuMuon { get; set; }
        public byte[] Avatar { get; set; }
    }
}
