//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTVEntities : DbContext
    {
        public QLTVEntities()
            : base("name=QLTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DanhGiaSach> DanhGiaSach { get; set; }
        public virtual DbSet<MuonTraSach> MuonTraSach { get; set; }
        public virtual DbSet<NguoiDung> NguoiDung { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhieuMuonSach> PhieuMuonSach { get; set; }
        public virtual DbSet<Sach> Sach { get; set; }
        public virtual DbSet<TaiKhoanNguoiDung> TaiKhoanNguoiDung { get; set; }
        public virtual DbSet<TaiKhoanNhanVien> TaiKhoanNhanVien { get; set; }
    }
}
