//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public int IDSach { get; set; }
        public string NgonNgu { get; set; }
        public string PhienBan { get; set; }
        public string TenSach { get; set; }
        public string TacGia { get; set; }
        public string TheLoai { get; set; }
        public string ChuyenNganh { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string NhaXuatBan { get; set; }
        public Nullable<System.DateTime> NamXuatBan { get; set; }
        public string GioiThieu { get; set; }
        public byte[] Avatar { get; set; }
    }
}
