//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanNhanVien
    {
        public int IDTaiKhoanNhanVien { get; set; }
        public Nullable<int> IDNhanVien { get; set; }
        public string ChucVu { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
    }
}
